apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: quay.io/20231232/eventhub-auth:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: eventhub
            - name: PGPASSWORD
              value: eventhub
            - name: PGDATABASE
              value: eventhub_auth
            - name: JWT_SECRET
              value: change-me-in-every-environment
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - port: 8082
      targetPort: 8082
