apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
        - name: notification-worker
          image: quay.io/20231232/eventhub-notification-worker:latest
          env:
            - name: RABBITMQ_URL
              value: amqp://eventhub:eventhub@rabbitmq:5672/
            - name: RABBITMQ_QUEUE
              value: bookings
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
